version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: api/Dockerfile
    network_mode: host
    volumes:
      - ./api:/app
      - /var/www/quizbotadmin/staticfiles:/app/staticfiles
      - /var/www/quizbotadmin/media:/app/media
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    container_name: web

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - ./bot:/app
      - /var/www/quizbotadmin/media:/app/media
    env_file:
      - .env
    network_mode: host
    container_name: bot
