version: '3.8'


services:

  web:
    build:
      context: .
      dockerfile: api/Dockerfile
    network_mode: host
    volumes:
      - ./api:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - ./bot:/app
    env_file:
      - .env
    network_mode: host

networks:
  app-network:
    driver: bridge
