# Generated by Django 5.2.4 on 2025-07-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertoken',
            options={'verbose_name': 'Токен игрока', 'verbose_name_plural': 'Токены игроков'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Квиз', 'verbose_name_plural': 'Квизы'},
        ),
        migrations.AlterModelOptions(
            name='telegramplayer',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='playertoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='playertoken',
            name='key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='playertoken',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='main.telegramplayer', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('variant', 'Variant')], max_length=255, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='main.topic', verbose_name='Темы'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz', verbose_name='Викторина'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='text',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='amount_questions',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Количество вопросов'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название викторины'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('team', 'TM'), ('single', 'SN'), ('death match', 'DM')], max_length=255, verbose_name='Тип викторины'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_to_answer',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Время на ответ'),
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='lang_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(verbose_name='Описание темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название темы'),
        ),
    ]
