# Generated by Django 5.2.4 on 2025-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_playertoken_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='main.question', verbose_name='Вопросы'),
        ),
    ]
