# Generated by Django 5.2.4 on 2025-07-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_questionanswer_quiz_quiz_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playertoken',
            old_name='player',
            new_name='user',
        ),
    ]
