# Generated by Django 5.2.4 on 2025-07-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_player_playertoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
