# Generated by Django 5.2.4 on 2025-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_playertoken_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertoken',
            name='is_active',
        ),
        migrations.AddField(
            model_name='telegramplayer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
