# Generated by Django 5.2.4 on 2025-07-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_playertoken_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playertoken',
            old_name='user',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='telegramplayer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
