# Generated by Django 5.2.4 on 2025-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user_playertoken_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('team', 'TM'), ('single', 'SN'), ('dm', 'DM')], max_length=255, verbose_name='Тип викторины'),
        ),
    ]
