# Generated by Django 5.2.4 on 2025-08-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('team', 'TM'), ('solo', 'SL'), ('dm', 'DM')], max_length=255, verbose_name='Тип викторины'),
        ),
    ]
