# Generated by Django 5.2.4 on 2025-08-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('chat_username', models.CharField(max_length=255, unique=True, verbose_name='Telegram username чата')),
                ('total_scores', models.PositiveIntegerField(default=0, verbose_name='Общий счет')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telegramplayer', verbose_name='Капитан')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
