# Generated by Django 5.2.4 on 2025-08-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramplayer',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущий стрик (дней)'),
        ),
        migrations.AddField(
            model_name='telegramplayer',
            name='last_played_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя игра'),
        ),
        migrations.AddField(
            model_name='telegramplayer',
            name='notification_is_on',
            field=models.BooleanField(default=True, verbose_name='Уведомления включены'),
        ),
        migrations.AddField(
            model_name='telegramplayer',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий XP'),
        ),
        migrations.CreateModel(
            name='PlanTeamQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Дата проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_team_quizzes', to='main.quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Запланированная командная игра',
                'verbose_name_plural': 'Запланированные командные игры',
            },
        ),
    ]
