# Generated by Django 5.2.4 on 2025-08-21 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_telegramplayer_current_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planteamquiz',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='planteamquiz',
            name='scheduled_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время проведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
