# Generated by Django 5.2.4 on 2025-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=255, unique=True, verbose_name='ID текста')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название текста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание текста')),
                ('unformatted_text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
