# Generated by Django 5.2.4 on 2025-08-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_bottext'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterModelOptions(
            name='bottext',
            options={'verbose_name': 'Текст бота', 'verbose_name_plural': 'Тексты бота'},
        ),
        migrations.AddField(
            model_name='question',
            name='game_use_type',
            field=models.CharField(choices=[('dm', 'DM'), ('solo', 'Solo')], default='dm', max_length=255, verbose_name='Тип игры для вопроса'),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
    ]
