# Generated by Django 5.2.4 on 2025-08-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_city_alter_bottext_options_question_game_use_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='game_use_type',
            field=models.CharField(blank=True, choices=[('dm', 'Соревновательный'), ('solo', 'Соло')], max_length=255, null=True, verbose_name='Тип игры для вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый'), ('variant', 'Варианты')], max_length=255, verbose_name='Тип вопроса'),
        ),
        migrations.CreateModel(
            name='QuestionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_type', models.CharField(choices=[('dm', 'DM'), ('solo', 'SOLO')], max_length=10, verbose_name='Тип использования')),
                ('context_id', models.BigIntegerField(verbose_name='Контекст (chat_id или telegram_id)')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='main.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Использование вопроса',
                'verbose_name_plural': 'Использования вопросов',
                'indexes': [models.Index(fields=['use_type', 'context_id', 'used_at'], name='main_questi_use_typ_991688_idx')],
                'unique_together': {('use_type', 'context_id', 'question')},
            },
        ),
    ]
