# Generated by Django 5.2.4 on 2025-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_question_game_use_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planteamquiz',
            name='always_active',
            field=models.BooleanField(default=False, verbose_name='Всегда активен'),
        ),
        migrations.AddField(
            model_name='planteamquiz',
            name='teams_played',
            field=models.ManyToManyField(blank=True, related_name='played_team_quizzes', to='main.team', verbose_name='Команды, сыгравшие в эту игру'),
        ),
        migrations.AlterField(
            model_name='planteamquiz',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='main.topic', verbose_name='Темы'),
        ),
    ]
