# Generated by Django 5.2.4 on 2025-08-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='planteamquiz',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='Отправить уведомление в чаты команд'),
        ),
    ]
