# Generated by Django 5.2.4 on 2025-09-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_planteamquiz_send_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('chat_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chat username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='PlayerInChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки в чате')),
                ('last_played_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя игра в чате')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='main.chat', verbose_name='Чат')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_scores', to='main.telegramplayer', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игрок в чате',
                'verbose_name_plural': 'Игроки в чатах',
                'constraints': [models.UniqueConstraint(fields=('player', 'chat'), name='unique_player_chat')],
            },
        ),
    ]
