# Generated by Django 5.2.4 on 2025-09-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_historicalbottext_historicalconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Chat username'),
        ),
    ]
